# Form implementation generated from reading ui file 'senderUI.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(815, 559)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(parent=Form)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 10, 611, 191))
        self.plainTextEdit.setPlainText("")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.pushButton = QtWidgets.QPushButton(parent=Form)
        self.pushButton.setGeometry(QtCore.QRect(640, 10, 141, 91))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_2.setGeometry(QtCore.QRect(640, 110, 141, 91))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(10, 210, 41, 21))
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(parent=Form)
        self.comboBox.setGeometry(QtCore.QRect(100, 210, 101, 31))
        self.comboBox.setObjectName("comboBox")
        self.textBrowser = QtWidgets.QTextBrowser(parent=Form)
        self.textBrowser.setGeometry(QtCore.QRect(10, 250, 341, 291))
        self.textBrowser.setObjectName("textBrowser")
        self.table1 = QtWidgets.QTableWidget(parent=Form)
        self.table1.setGeometry(QtCore.QRect(370, 250, 411, 291))
        self.table1.setObjectName("table1")
        self.table1.setColumnCount(4)
        self.table1.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table1.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table1.setHorizontalHeaderItem(3, item)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.plainTextEdit.setPlaceholderText(_translate("Form", "输入待发送的数据"))
        self.pushButton.setText(_translate("Form", "成帧"))
        self.pushButton_2.setText(_translate("Form", "发送"))
        self.label.setText(_translate("Form", "帧信息"))
        item = self.table1.horizontalHeaderItem(0)
        item.setText(_translate("Form", "序号"))
        item = self.table1.horizontalHeaderItem(1)
        item.setText(_translate("Form", "数据"))
        item = self.table1.horizontalHeaderItem(2)
        item.setText(_translate("Form", "发送"))
        item = self.table1.horizontalHeaderItem(3)
        item.setText(_translate("Form", "接受"))
